### ISSUE TITLE
Exception on /up

### ISSUE THREAD

**Issue by caioavidal** [OpenCoreMMO/OpenCoreMMO#205]
![image](https://user-images.githubusercontent.com/11817846/129480133-0ff1d49e-fb61-43fe-b385-f85d92b7ed6a.png)
![image](https://user-images.githubusercontent.com/11817846/129480136-2efa52c7-05ee-40bb-959c-88a0571584eb.png)

**Comment by Shelby115** [comment]
The exception is being thrown because going vertically up/down the `Direction` property in `Creature.cs` is a value of `Direction.None` which when `SafeDirection` is called hits the default and throws the `ArgumentOutOfRangeException`.

When I had the default return `Direction.None` instead, the up and down commands would work, but the player would be invisible afterwards until they moved.

We could default the value to `Direction.South` and then the player wouldn't be invisible. Another alternative would be to track the creature's last direction they were facing and use that as the default for `SafeDirection`.

What are your thoughts on this? I haven't dug into everything that uses the `SafeDirection` property yet so I'm not sure what the consequences are for removing the default `ArgumentOutOfRangeException`.

I did notice that the ladder seems to work just fine, so I will look into this further another day.

**Comment by caioavidal** [comment]
"Another alternative would be to track the creature's last direction they were facing and use that as the default for SafeDirection."

nod that is a viable solution. I think we can remove that Exception as it makes no sense for me. So we can track the last direction and set it to SafeDirection. +1
